# -*- coding: utf-8 -*-
"""Log-analiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EyHmoTSt5qDANuB6mImbAoJUlgMq8XUm
"""

log_icerigi = """
May 20 12:31:14 server sshd[1200]: Failed password for invalid user admin from 192.168.1.12 port 4455 ssh2
May 20 12:35:02 server sshd[1200]: Accepted password for user1 from 192.168.1.5 port 4433 ssh2
May 20 12:39:50 server sshd[1200]: Failed password for root from 192.168.1.50 port 4422 ssh2
"""

with open("log.txt", "w") as dosya:
    dosya.write(log_icerigi)

import re

# IP adreslerini tutmak için boş bir liste oluşturuyoruz
ip_listesi = []

# log dosyasını okuyoruz
with open("log.txt", "r") as dosya:
    log_satirlari = dosya.readlines()

# "Failed password" satırlarını bulup IP adreslerini çıkarıyoruz
for satir in log_satirlari:
    if "Failed password" in satir:
        # IP adresi düzenli ifadesi: xxx.xxx.xxx.xxx (0-255 arası)
        ip_eslesme = re.search(r"from (\d+\.\d+\.\d+\.\d+)", satir)
        if ip_eslesme:
            ip = ip_eslesme.group(1)  # Eşleşen IP adresini al
            ip_listesi.append(ip)

# IP listesini yazdırıyoruz
print("Tespit edilen şüpheli IP adresleri:")
for ip in ip_listesi:
    print(ip)

